import { AccountTreeOutlined, AppsOutlined, ChatOutlined, DashboardOutlined, KeyOutlined, LogoutOutlined, PhoneOutlined, SettingsOutlined, SmartToyOutlined, VpnKeyOutlined } from '@mui/icons-material';
import { AppBar, Box, CssBaseline, Drawer, IconButton, List, ListItemButton, ListItemIcon, ListItemText, ThemeProvider, Toolbar, Typography, createTheme } from '@mui/material';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { NavLink, Navigate, Outlet, Route, Routes, useNavigate } from 'react-router-dom';
import { BrowserRouter } from 'react-router-dom';
import { authStorage } from '../services/auth-storage';
import { LoginPage } from '../modules/auth/LoginPage';
import { DashboardPage } from '../modules/dashboard/DashboardPage';
import { CredentialsPage } from '../modules/credentials/CredentialsPage';
import { AdministrationPage } from '../modules/administration/AdministrationPage';
import { MessagesPage } from '../modules/messages/MessagesPage';
import { TemplatesPage } from '../modules/templates/TemplatesPage';

const queryClient = new QueryClient({ defaultOptions: { queries: { retry: 1, refetchOnWindowFocus: false } } });
const theme = createTheme({ palette: { primary: { main: '#075e54' }, secondary: { main: '#25d366' }, background: { default: '#f5f7f6' } }, shape: { borderRadius: 10 }, typography: { fontFamily: 'Inter, Roboto, Arial, sans-serif' } });
const menu = [{ to: '/', label: 'Visão geral', icon: <DashboardOutlined /> }, { to: '/tenants', label: 'Tenants', icon: <AccountTreeOutlined /> }, { to: '/applications', label: 'Aplicações', icon: <AppsOutlined /> }, { to: '/whatsapp-accounts', label: 'Contas WhatsApp', icon: <SmartToyOutlined /> }, { to: '/phone-numbers', label: 'Números', icon: <PhoneOutlined /> }, { to: '/api-keys', label: 'API keys', icon: <VpnKeyOutlined /> }, { to: '/credentials', label: 'Credenciais', icon: <KeyOutlined /> }, { to: '/messages', label: 'Mensagens', icon: <ChatOutlined /> }, { to: '/templates', label: 'Templates', icon: <SettingsOutlined /> }];
function Layout() { const navigate = useNavigate(); const logout = () => { authStorage.removeSessionToken(); authStorage.removeApiKey(); queryClient.clear(); navigate('/login'); }; return <Box sx={{ display: 'flex', minHeight: '100vh' }}><AppBar position="fixed" elevation={0}><Toolbar><Typography variant="h6" sx={{ flexGrow: 1 }}>Message Hub Console</Typography><IconButton aria-label="Sair" color="inherit" onClick={logout}><LogoutOutlined /></IconButton></Toolbar></AppBar><Drawer variant="permanent" sx={{ width: 252, flexShrink: 0, '& .MuiDrawer-paper': { width: 252, boxSizing: 'border-box', pt: 8 } }}><List>{menu.map((item) => <ListItemButton key={item.to} component={NavLink} to={item.to} end={item.to === '/'}><ListItemIcon>{item.icon}</ListItemIcon><ListItemText primary={item.label} /></ListItemButton>)}</List></Drawer><Box component="main" sx={{ flexGrow: 1, p: { xs: 2, md: 4 }, pt: { xs: 10, md: 12 }, maxWidth: 1500 }}><Outlet /></Box></Box>; }
function ProtectedRoute() { return authStorage.getSessionToken() ? <Layout /> : <Navigate to="/login" replace />; }
export function App() { return <ThemeProvider theme={theme}><CssBaseline /><QueryClientProvider client={queryClient}><BrowserRouter><Routes><Route path="/login" element={authStorage.getSessionToken() ? <Navigate to="/" replace /> : <LoginPage />} /><Route element={<ProtectedRoute />}><Route path="/" element={<DashboardPage />} /><Route path="/tenants" element={<AdministrationPage kind="tenants" />} /><Route path="/applications" element={<AdministrationPage kind="applications" />} /><Route path="/whatsapp-accounts" element={<AdministrationPage kind="whatsapp-accounts" />} /><Route path="/phone-numbers" element={<AdministrationPage kind="phone-numbers" />} /><Route path="/api-keys" element={<AdministrationPage kind="api-keys" />} /><Route path="/credentials" element={<CredentialsPage />} /><Route path="/messages" element={<MessagesPage />} /><Route path="/templates" element={<TemplatesPage />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes></BrowserRouter></QueryClientProvider></ThemeProvider>; }
