import { zodResolver } from '@hookform/resolvers/zod';
import { Alert, Button, Card, CardContent, Grid, MenuItem, Stack, TextField } from '@mui/material';
import { useMutation } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { EntityResult } from '../../components/shared/EntityResult';
import { PageHeader } from '../../components/ui/PageHeader';
import { administrationApi, type Entity } from './administration.api';

type Kind = 'tenants' | 'applications' | 'whatsapp-accounts' | 'phone-numbers' | 'api-keys';
const config: Record<Kind, { title: string; description: string; schema: z.ZodTypeAny; fields: { name: string; label: string; type?: string; options?: string[] }[]; create: (data: Record<string, string>) => Promise<Entity>; lookup?: (id: string) => Promise<Entity> }> = {
  tenants: { title: 'Tenants', description: 'Crie tenants ou consulte um tenant já cadastrado por ID.', schema: z.object({ name: z.string().min(2, 'Informe ao menos 2 caracteres.') }), fields: [{ name: 'name', label: 'Nome do tenant' }], create: ({ name }) => administrationApi.createTenant(name), lookup: administrationApi.getTenant },
  applications: { title: 'Aplicações', description: 'Vincule uma aplicação consumidora a um tenant.', schema: z.object({ tenantId: z.string().uuid('Informe um UUID válido.'), name: z.string().min(2) }), fields: [{ name: 'tenantId', label: 'ID do tenant' }, { name: 'name', label: 'Nome da aplicação' }], create: (data) => administrationApi.createApplication(data as { tenantId: string; name: string }) },
  'whatsapp-accounts': { title: 'Contas WhatsApp', description: 'Registre a WABA e a origem segura das credenciais.', schema: z.object({ tenantId: z.string().uuid(), wabaId: z.string().min(1), credentialSource: z.enum(['default', 'tenant']), accessToken: z.string().optional(), appSecret: z.string().optional() }), fields: [{ name: 'tenantId', label: 'ID do tenant' }, { name: 'wabaId', label: 'WABA ID' }, { name: 'credentialSource', label: 'Origem da credencial', options: ['default', 'tenant'] }, { name: 'accessToken', label: 'Access token (somente origem tenant)', type: 'password' }, { name: 'appSecret', label: 'App secret (opcional)', type: 'password' }], create: administrationApi.createAccount, lookup: administrationApi.getAccount },
  'phone-numbers': { title: 'Números de telefone', description: 'Registre um número da Meta vinculado a uma conta WhatsApp.', schema: z.object({ whatsAppAccountId: z.string().uuid(), phoneNumberId: z.string().min(1), displayNumber: z.string().min(1) }), fields: [{ name: 'whatsAppAccountId', label: 'ID da conta WhatsApp' }, { name: 'phoneNumberId', label: 'Phone Number ID (Meta)' }, { name: 'displayNumber', label: 'Número de exibição' }], create: (data) => administrationApi.createPhoneNumber(data as { whatsAppAccountId: string; phoneNumberId: string; displayNumber: string }), lookup: administrationApi.getPhoneNumber },
  'api-keys': { title: 'API keys', description: 'Gere ou revogue chaves para uma aplicação. O valor completo é exibido apenas uma vez.', schema: z.object({ applicationId: z.string().uuid(), type: z.enum(['platform', 'tenant']), expiresAt: z.string().optional() }), fields: [{ name: 'applicationId', label: 'ID da aplicação' }, { name: 'type', label: 'Tipo', options: ['platform', 'tenant'] }, { name: 'expiresAt', label: 'Expira em (opcional)', type: 'datetime-local' }], create: ({ applicationId, type, expiresAt }) => administrationApi.createApiKey(applicationId, { type, ...(expiresAt ? { expiresAt } : {}) }) },
};

export function AdministrationPage({ kind }: { kind: Kind }) {
  const current = config[kind];
  const form = useForm<Record<string, string>>({ resolver: zodResolver(current.schema) as never, defaultValues: { type: 'platform', credentialSource: 'default' } });
  const create = useMutation({ mutationFn: current.create });
  const lookup = useMutation({ mutationFn: (id: string) => current.lookup ? current.lookup(id) : Promise.reject(new Error('Consulta não disponível.')) });
  const result = create.data ?? lookup.data ?? null;
  return <Stack spacing={3}><PageHeader title={current.title} description={current.description} /><Grid container spacing={3}><Grid size={{ xs: 12, md: 7 }}><Card variant="outlined"><CardContent><Stack component="form" spacing={2} onSubmit={form.handleSubmit((data) => create.mutate(data))}>{create.error && <Alert severity="error">{create.error.message}</Alert>}{current.fields.map((field) => <TextField key={field.name} label={field.label} type={field.type} select={!!field.options} {...form.register(field.name)} error={!!form.formState.errors[field.name]} helperText={form.formState.errors[field.name]?.message} fullWidth>{field.options?.map((option) => <MenuItem key={option} value={option}>{option}</MenuItem>)}</TextField>)}<Button type="submit" variant="contained" disabled={create.isPending}>{create.isPending ? 'Salvando...' : 'Salvar'}</Button></Stack></CardContent></Card></Grid><Grid size={{ xs: 12, md: 5 }}><Card variant="outlined"><CardContent><EntityResult title="Resultado" data={result} />{kind === 'api-keys' && create.data && <Alert severity="warning" sx={{ mt: 2 }}>Copie a chave agora: {String(create.data.plainTextKey)}</Alert>}</CardContent></Card></Grid>{current.lookup && <Grid size={12}><Card variant="outlined"><CardContent><Stack direction={{ xs: 'column', sm: 'row' }} component="form" spacing={2} onSubmit={(event) => { event.preventDefault(); const id = new FormData(event.currentTarget).get('id'); if (typeof id === 'string' && id) lookup.mutate(id); }}><TextField name="id" label="Consultar por ID" fullWidth /><Button type="submit" variant="outlined" disabled={lookup.isPending}>Consultar</Button></Stack>{lookup.error && <Alert severity="error" sx={{ mt: 2 }}>{lookup.error.message}</Alert>}</CardContent></Card></Grid>}</Grid></Stack>;
}
