import { zodResolver } from '@hookform/resolvers/zod';
import { Alert, Button, Card, CardContent, Chip, Grid, Stack, TextField, Typography } from '@mui/material';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { AsyncState } from '../../components/shared/AsyncState';
import { PageHeader } from '../../components/ui/PageHeader';
import { templatesApi } from './templates.api';

const schema = z.object({ whatsAppAccountId: z.string().uuid(), name: z.string().min(1), language: z.string().min(2), category: z.string().min(1), body: z.string().min(1) });
type FormData = z.infer<typeof schema>;
export function TemplatesPage() { const form = useForm<FormData>({ resolver: zodResolver(schema), defaultValues: { language: 'pt_BR', category: 'UTILITY' } }); const accountId = form.watch('whatsAppAccountId'); const client = useQueryClient(); const list = useQuery({ queryKey: ['templates', accountId], queryFn: () => templatesApi.list(accountId), enabled: z.string().uuid().safeParse(accountId).success }); const create = useMutation({ mutationFn: templatesApi.create, onSuccess: () => client.invalidateQueries({ queryKey: ['templates', accountId] }) }); const sync = useMutation({ mutationFn: templatesApi.sync, onSuccess: () => client.invalidateQueries({ queryKey: ['templates', accountId] }) }); return <Stack spacing={3}><PageHeader title="Templates" description="Cadastre e sincronize templates da conta WhatsApp selecionada." /><Grid container spacing={3}><Grid size={{ xs: 12, md: 5 }}><Card variant="outlined"><CardContent><Stack component="form" spacing={2} onSubmit={form.handleSubmit((data) => create.mutate(data))}>{create.error && <Alert severity="error">{create.error.message}</Alert>}<TextField label="ID da conta WhatsApp" {...form.register('whatsAppAccountId')} error={!!form.formState.errors.whatsAppAccountId} helperText={form.formState.errors.whatsAppAccountId?.message} /><TextField label="Nome" {...form.register('name')} /><TextField label="Idioma" {...form.register('language')} /><TextField label="Categoria" {...form.register('category')} /><TextField label="Texto do corpo" multiline minRows={4} {...form.register('body')} /><Button type="submit" variant="contained" disabled={create.isPending}>Criar template</Button><Button type="button" variant="outlined" onClick={() => sync.mutate(accountId)} disabled={!accountId || sync.isPending}>Sincronizar com Meta</Button>{sync.data && <Alert severity="success">Sincronização concluída: {sync.data.total} templates processados.</Alert>}</Stack></CardContent></Card></Grid><Grid size={{ xs: 12, md: 7 }}><Card variant="outlined"><CardContent><Typography variant="h6" gutterBottom>Templates disponíveis</Typography><AsyncState isLoading={list.isLoading} error={list.error}>{list.data?.length ? <Stack spacing={1}>{list.data.map((template) => <Card key={template.id} variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between" alignItems="center"><div><Typography fontWeight={600}>{template.name}</Typography><Typography variant="body2" color="text.secondary">{template.language} · {template.category}</Typography></div><Chip label={template.status} size="small" /></Stack></CardContent></Card>)}</Stack> : <Typography color="text.secondary">Informe uma conta válida para listar os templates.</Typography>}</AsyncState></CardContent></Card></Grid></Grid></Stack>; }
